### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by virtuald** [auscompgeek/sphinxify#1]
```
>>> import sphinxify
>>> input = '*\n* Sends an error to the driver station.\n*\n* @param isError   true for error, false for warning\n* @param errorCode the error code\n* @param isLVCode  true for a LV error code, false for a standard error code\n* @param details   the details of the error\n* @param location  the file location of the errror\n* @param callstack the callstack of the error\n* @param printMsg  true to print the error message to stdout as well as to the\n* DS\n*/'
>>> sphinxify.process_raw(input)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sphinxify.py", line 196, in process_raw
    return process_doc(s[0])
  File "sphinxify.py", line 151, in process_doc
    return str(Doc.from_comment(txt))
  File "sphinxify.py", line 145, in __str__
    return self.text + "\n".join(to_append)
AttributeError: 'Doc' object has no attribute 'text'
```

**Comment by auscompgeek** [comment]
... wow I really need tests

**Comment by virtuald** [comment]
Setting up some basic tests would be useful.
